# Generated by Django 4.2.5 on 2023-12-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab_m', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
